version: "3.9"

services:
  app:
    container_name: app
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
  db:
    container_name: db_postgres
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    expose:
      - 5432

  py_admin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    depends_on:
      - app
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  postgres_data:
